project:
  type: manuscript
execute:
  freeze: auto
manuscript:
  code-links: 
    - text: MAPME
      icon: globe-europe-africa
      href: https://www.mapme-initiative.org/
    - text: GitHub
      icon: github
      href: https://github.com/mapme-initiative/demo-madeira/
format:
  html:
    code-link: true
    theme: theme.scss
    comments:
      hypothesis: true
